### ISSUE TITLE
Proposal : Add support for multiple parameters

### ISSUE THREAD

**Issue by wild006** [VircomOpenSource/DbAutoFill#3]
## Problematic Case 
Consider the case where you have a stored procedure as follows: 
`DeleteGroup(AdminUserId, GroupId)`

In this peculiar case, we do *not* have a structure like the following:
```
class GroupAdmin
{
public int AdminUserId; 
public int GroupId; 
}
``` 

Indeed, we consider creating an object for this quite useless... ? 

## Solution 1 
The proposal would be to add an overload to the method : 
`ExecuteDbProcedureNameAsCallerName(params[] objects...)`

Indeed, it would take a variable count of objects (tagged with `DbAutoFillAttribute`). 
It would merge the members. 

### Possible Issue: Duplicate Members 
To avoid this kind of error, allow only DbAnonymousValue instead of complex classes. This forces no-collision. 

Or alternatively, allow complex types to merge, but throw exception on duplicate members -> this will throw an exception

Or, just silently override. 

### Sample 
``` 
DbAnonymousValue<int> groupId = new DbAnonymousValue<int>("groupId", 2);
DbAnonymousValue<int> adminId = new DbAnonymousValue<int>("adminId", 45);
commandHelper.ExecuteDbProcedureNameAsCallerName(groupId, adminId);
``` 

## Solution 2 
The other proposal would be to add a type DbParameterUnion where objects are added to it but get treated differently than asimple list (flatten the list instead of acting like a structured type).  

### Possible Issue: Special Treatment 
Indeed, I think it would force a special type treatment within the library and therefore is a bigger modification to the core, instead of just a layer of the library. 
 
### Sample 
``` 
DbParameterUnion pu = new DbParameterUnion({"groupId", 2}, {"adminId", 45}); 
commandHelper.ExecuteDbProcedureNameAsCallerName(pu);
``` 

## Workaround: 
Right now, we creates wrapper. It's ugly, but it works...

**Comment by mrtryhard** [comment]
This is indeed a limitation right now. 
I would opt for the function overloading, I do believe it is the easiest to implement.

I'll see the options and come at it later.

**Comment by mrtryhard** [comment]
The proposal with `params[]` cannot be done exactly with params itself but with an array of object, instead. 
The scope of the changes is limited to `DbCommandHelper.cs` only, with a little rework (add iteration). It shouldn't be too hard to achieve this. 

The other proposal unfortunately, requires a lot of changes; 
It needs to get treated as a special type which would need a change into the DbAutoFillHelper which wouldn't be light. This adds complexity and is bug prone. 


But the overload proposal is light and easy to implement. 
@jsvircom ?

**Comment by jsvircom** [comment]
Agree @mrtryhard, let's go with the overload proposal.

**Comment by mrtryhard** [comment]
Feature implemented. Thanks.
